### ISSUE TITLE
disable keepalive

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglacio-hubot#1]
We're on heroku and we don't need that keepalive thing :)

``` text
2015-07-04T16:22:33.358975+00:00 app[web.1]:   at errnoException (net.js:905:11)
2015-07-04T16:22:33.358977+00:00 app[web.1]:   at Object.afterConnect [as oncomplete] (net.js:896:19)
2015-07-04T16:22:33.358979+00:00 app[web.1]:
2015-07-04T16:27:33.427525+00:00 app[web.1]: [Sat Jul 04 2015 16:27:33 GMT+0000 (UTC)] INFO keepalie pong: Error: connect ECONNREFUSED
2015-07-04T16:27:33.425901+00:00 app[web.1]: [Sat Jul 04 2015 16:27:33 GMT+0000 (UTC)] INFO keepalive ping
2015-07-04T16:27:33.438028+00:00 app[web.1]: [Sat Jul 04 2015 16:27:33 GMT+0000 (UTC)] ERROR Error: connect ECONNREFUSED
2015-07-04T16:27:33.438032+00:00 app[web.1]:   at errnoException (net.js:905:11)
2015-07-04T16:27:33.438034+00:00 app[web.1]:   at Object.afterConnect [as oncomplete] (net.js:896:19)
2015-07-04T16:27:33.438036+00:00 app[web.1]:
```

**Comment by GabLeRoux** [comment]
https://github.com/github/hubot/issues/827
https://github.com/github/generator-hubot/issues/25

**Comment by GabLeRoux** [comment]
Oh, we're still on the free dyno at this time

```
2015-07-04T17:08:46.866510+00:00 app[web.1]: [Sat Jul 04 2015 17:08:46 GMT+0000 (UTC)] INFO Connecting...
2015-07-04T17:08:47.091943+00:00 app[web.1]: [Sat Jul 04 2015 17:08:47 GMT+0000 (UTC)] INFO Logged in as hubot of io, but not yet connected
2015-07-04T17:08:47.233449+00:00 app[web.1]: [Sat Jul 04 2015 17:08:47 GMT+0000 (UTC)] INFO Slack client now connected
2015-07-04T17:08:47.569733+00:00 app[web.1]: [Sat Jul 04 2015 17:08:47 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
2015-07-04T17:13:46.634577+00:00 app[web.1]: [Sat Jul 04 2015 17:13:46 GMT+0000 (UTC)] INFO keep alive ping!
2015-07-04T17:18:46.636358+00:00 app[web.1]: [Sat Jul 04 2015 17:18:46 GMT+0000 (UTC)] INFO keep alive ping!
2015-07-04T17:23:46.641519+00:00 app[web.1]: [Sat Jul 04 2015 17:23:46 GMT+0000 (UTC)] INFO keep alive ping!
2015-07-04T17:28:46.645518+00:00 app[web.1]: [Sat Jul 04 2015 17:28:46 GMT+0000 (UTC)] INFO keep alive ping!
2015-07-04T17:33:46.648874+00:00 app[web.1]: [Sat Jul 04 2015 17:33:46 GMT+0000 (UTC)] INFO keep alive ping!
2015-07-04T17:38:46.651577+00:00 app[web.1]: [Sat Jul 04 2015 17:38:46 GMT+0000 (UTC)] INFO keep alive ping!
2015-07-04T17:42:24.612126+00:00 heroku[web.1]: Idling
2015-07-04T17:42:24.612841+00:00 heroku[web.1]: State changed from up to down
2015-07-04T17:42:27.124224+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-07-04T17:42:28.611360+00:00 heroku[web.1]: Process exited with status 0
```

Enabling it again :P
